spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  socketio:
    port: ${SOCKET_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secretKey: ${SECRET_KEY}
  accessTokenExp: ${ACCESS_EXP}
  refreshTokenExp: ${REFRESH_EXP}

server:
  port: 8181
  servlet:
    context-path: /v1
  shutdown: graceful

logging:
  level:
    root: error

oauth2:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    redirectUrl: ${GOOGLE_REDIRECT_URL}
    scope: ${GOOGLE_SCOPE}
  github:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    redirectUrl: ${GOOGLE_REDIRECT_URL}
    scope: ${GOOGLE_SCOPE}